[mypy]
python_version = 3.12
strict = True
warn_unreachable = True
mypy_path = src
explicit_package_bases = True
namespace_packages = True

[mypy-tests.*]
disallow_untyped_decorators = False

[mypy-ulid.*]
ignore_missing_imports = True
